# Generated by Django 2.0.3 on 2019-06-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_name', models.CharField(max_length=30, verbose_name='接口名称')),
                ('request', models.TextField(verbose_name='请求信息')),
            ],
            options={
                'verbose_name': '接口',
                'db_table': 'Api',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_name', models.CharField(max_length=30, verbose_name='用例名称')),
                ('step_list', models.TextField(verbose_name='步骤顺序')),
            ],
            options={
                'verbose_name': '用例',
                'db_table': 'Case',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module_name', models.CharField(max_length=30, verbose_name='模块名称')),
            ],
            options={
                'verbose_name': '模块信息',
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=30, unique=True, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('step_name', models.CharField(max_length=30, verbose_name='步骤名称')),
                ('request', models.TextField(verbose_name='请求信息')),
                ('belong_api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Module')),
            ],
            options={
                'verbose_name': '步骤',
                'db_table': 'Step',
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('suite_name', models.CharField(max_length=30, unique=True, verbose_name='集合名称')),
                ('case_list', models.TextField(verbose_name='用例集合')),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Module')),
            ],
            options={
                'verbose_name': '集合',
                'db_table': 'Suite',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='case',
            name='belong_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Module'),
        ),
        migrations.AddField(
            model_name='api',
            name='belong_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Module'),
        ),
    ]
